name: Local Assistant
version: 1.0.0
schema: v1

models:
  - name: Samantha Coder
    provider: openai
    model: sparksammy/samantha-coder-q2.5:smol
    env:
      useLegacyCompletionsEndpoint: false
    apiBase: https://ollama-api.nodemixaholic.com/v1
    apiKey: x
    roles:
      - chat
      - edit
      - autocomplete
  - name: Samantha Gemma 3 (SamGem3)
    provider: openai
    model: sparksammy/samgem:latest
    env:
      useLegacyCompletionsEndpoint: false
    apiBase: https://ollama-api.nodemixaholic.com/v1
    apiKey: x
    roles:
      - chat
      - edit
  - name: Samantha Thinker
    provider: openai
    model: sparksammy/samantha-thinker-v2:latest
    env:
      useLegacyCompletionsEndpoint: false
    apiBase: https://ollama-api.nodemixaholic.com/v1
    apiKey: x
    roles:
      - chat
      - edit

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase

