name: Local Assistant
version: 1.0.0
schema: v1

models:
  - name: Samantha LLAMA
    provider: openai
    model: samantha-llama-4-scout
    env:
      useLegacyCompletionsEndpoint: false
    apiBase: https://personal-ai.nodemixaholic.com/api
    apiKey: sk-756bf7f63b8c42589775e8efc28163bd
    roles:
      - chat
      - edit
  - name: Samantha GROK
    provider: openai
    model: samantha-grok
    env:
      useLegacyCompletionsEndpoint: false
    apiBase: https://personal-ai.nodemixaholic.com/api
    apiKey: sk-756bf7f63b8c42589775e8efc28163bd
    roles:
      - chat
      - edit
- name: ROBLOX Assistant
    provider: openai
    model: openai-roblox-withprompt
    env:
      useLegacyCompletionsEndpoint: false
    apiBase: https://personal-ai.nodemixaholic.com/api
    apiKey: sk-756bf7f63b8c42589775e8efc28163bd
    roles:
      - chat
      - edit
  - name: Samantha Coder
    provider: openai
    model: sparksammy/samantha-coder-q2.5:smolr
    env:
      useLegacyCompletionsEndpoint: false
    apiBase: https://personal-ai.nodemixaholic.com/api
    apiKey: sk-756bf7f63b8c42589775e8efc28163bd
    roles:
      - chat
      - edit
      - autocomplete

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase

